- name: "Installing"
  block:
    - name: "Add Debian repository"
      apt_repository:
        repo: deb http://ftp.ru.debian.org/debian/ {{ ansible_facts['lsb']['codename'] }} main contrib
        state: present
      when: add_system_repo == "yes"

    - name: "Install the {{ java.version.debian[ansible_facts['lsb']['codename']] }} version of OpenJDK"
      apt:
        name: openjdk-{{ java.version.debian[ansible_facts['lsb']['codename']] }}-jre

  when: state == "started"

#
#- name: "Uninstalling"
#  block:
#    - name: "Uninstall Java"
#      yum:
#        name: java-{{ java_version }}-openjdk
#        autoremove: yes
#        state: absent
#    - name: "Delete CentOS repository"
#      file:
#        path: /etc/yum.repos.d/centos-updates.repo
#        force: true
#        state: absent
#      when: add_system_repo is defined
#  when: state == "absent"
